config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :pitch_cards, except: :index  do
    collection do
      get :initiated, :collabs, :search
    end
    member do
      post :complete, :activate
    end
    resources :comments, only: [:index, :new, :create, :update, :destroy, :initiator_scope, :accept] do
      member do
        post 'initiator_scope'
        post 'accept'
      end
    end
    resources :suggestions, only: [:index, :new, :create, :update, :destroy, :accept] do
      member do
        post 'accept'
      end
    end
  end

  authenticated :user do
    root :to => "dashboard#index", as: :authenticated_root
  end

  root 'welcome#index'

end

app/views/pitch_cards/partials/card/_card.html.erb
<div class="block block-bordered pitch-card">
  <%= hidden_field_tag 'pitch-card-id', @pitch_card._id %>

  <!-- Update pitch card -->
  <% if @pitch_card.initiator == current_user %>  
    <div align=right>
      <%= link_to(edit_pitch_card_path) do %>
        <i class="fa fa-pencil"></i> Update
      <% end %>
    </div>
  <% end %>
  <!-- END Update pitch card -->

  <div class="form-horizontal form-bordered">

	<% if @pitch_card.image.present? %>

		<div class="form-group">
		  <div class="col-md-12">

			<div class="wrapper">
			  <div class="photo-preview" style="background-image:url(<%= @pitch_card.image.url %>);">
			  </div>
			</div>

		  </div>
		</div>

	<% end %>

	<% @pitch_card.pitch_points.reject{|p| not p.selected}.each  do |pitch_point_model|

	  point = PitchPointsHelper.pitch_points_hash.select { |point|
		pitch_point_model.name == point[:name]
	  }

	  point = point.any? ? point.first : nil

	  # the pitch point must be specified in our pitch_point_hash
	  if point == nil
		# TODO better error
		raise Error
	  end

	%>

		<%= render partial: 'pitch_cards/partials/card/pitch_point', locals: { point: point, pitch_point_model: pitch_point_model } %>

	<% end %>

	<%= render partial: 'pitch_cards/partials/discourses/suggestions/new', locals: {} %>

	<% initiator = @pitch_card.initiator %>
	<% can_see_initiator = can? :see_initiator, @pitch_card %>
	<% initiator_name = can_see_initiator ? initiator.first_name + " " + initiator.last_name : "Anonymous" %>
	<div class="form-group">
	  <div class="col-md-12">

		<div class="text-center">
		  Initiated by <%= initiator_name %> <abbr class="timeago" title="<%= @pitch_card.created_at.to_time.iso8601 %>"></abbr>
		  <% if @pitch_card.complete? %>
			  <br/><br/><label class="label label-success">completed</label>
		  <% end %>
		</div>

	  </div>
	</div>

  </div>

</div>

app/views/pitch_cards/partials/card/_messages.erb
<div>
  <h2 class="heading push-bottom text-center">Comments & Suggestions</h2>

  <div id="discourses-loader" class="preloader themed-background">
	<div class="inner">
	  <h3 class="visible-lt-ie9 visible-lt-ie10"><strong>Loading..</strong></h3>
	  <div class="preloader-spinner hidden-lt-ie9 hidden-lt-ie10"></div>
	</div>
  </div>

  <div id="discourses-empty" class="lead hidden">
	<h4 class="push-top-bottom text-center">Nothing here yet...</h4>
  </div>

  <div id="discourses-content" class="hidden">
	<% @pitch_card.pitch_points.reject{|p| not p.selected}.each  do |pitch_point_model|

	  point = PitchPointsHelper.pitch_points_hash.select { |point|
		pitch_point_model.name == point[:name]
	  }

	  point = point.any? ? point.first : nil

	  # the pitch point must be specified in our pitch_point_hash
	  if point == nil
		# TODO better error
		raise Error
	  end

	%>

		<%= render partial: 'pitch_cards/partials/card/pitch_point_discourse', locals: { point: point, pitch_point_model: pitch_point_model } %>

	<% end %>

  </div>

</div>

app/views/pitch_cards/partials/card/_mini_card.html.erb
<% value_proposition_image = 'points/selected/value_proposition.png'%>
<% center_attr = should_center ? "style=\"margin: 0 auto; margin-bottom: 20px;\"" : "" %>
<!--<%= center_attr.html_safe %>-->

<div class="col4 box" <%= center_attr.html_safe %>>

  <!-- image [optional] -->
  <% if pitch_card.image.present? %>
	  <div class="row push-bit" style="margin-left: 0px; margin-right: 0px;">
		<%= image_tag_with_at2x pitch_card.image.url, :class => "photo-view" %>
	  </div>
  <% end %>

  <!-- point-->
  <div class="push-bit">
	<div class="form-group">
	  <div class="row-same-height">
		<div class="col-xs-2 col-xs-height col-middle">
		  <div class="text-center">
			<%= image_tag_with_at2x value_proposition_image, :class =>  "pitch-point-image-restrained" %>
		  </div>
		</div>
		<% can_manage = can? :manage, pitch_card %>
		<% if can_manage %>
			<div class="col-xs-9 col-xs-height">
			  <%= text_area_tag "textarea-input", pitch_card.value_proposition, class: "form-horizontal form-control-borderless form-pitch-point", disabled: :true %>
			</div>
			<div class="col-xs-1 col-xs-height col-top">
			  <%= link_to pitch_card, method: :delete, data: { confirm: 'This will destroy the pitch card for good. Are you sure?' } do %>
				  <i class="fa fa-times delete-pitch delete-pitch-raised"></i>
			  <% end %>
			</div>
		<% else %>
			<div class="col-xs-10 col-xs-height">
			  <%= text_area_tag "textarea-input", pitch_card.value_proposition, class: "form-horizontal form-control-borderless form-pitch-point", disabled: :true %>
			</div>
		<% end %>
	  </div>
	</div>
  </div>

  <!-- seeking-->
  <%
	 seeking_points = []
	 pitch_card.pitch_points.each do |point|
	   if point.value.blank? && point.selected?
		 seeking_points << point[:name].downcase.tr(' ', '_')
	   end
	 end
  %>
  <% if seeking_points.any? %>
	  <div class="row push-bit">
		<div class="form-group">
		  <div class="col-sm-10 col-sm-offset-1 text-center">
			<% seeking_points.each do |point| %>
				<% image_selected = 'points/selected/'+point+'.png'%>
				<%= image_tag_with_at2x image_selected , size:"20x20" %>
			<% end %>
		  </div>
		</div>
	  </div>
  <% end %>

  <!-- author + time-->
  <% initiator = pitch_card.initiator %>
  <% can_see_initiator = can? :see_initiator, pitch_card %>
  <% initiator_name = can_see_initiator ? initiator.first_name + " " + initiator.last_name : "Anonymous" %>
  <div class="row push-bit">
	<div class="col-md-12">
	  <div class="text-center">
		Initiated by <%= initiator_name %> <abbr class="timeago" title="<%= pitch_card.created_at.to_time.iso8601 %>"></abbr>
		<% if pitch_card.complete? %>
			<br/><label class="label label-success">completed</label>
		<% end %>
	  </div>
	</div>
  </div>

  <%= link_to pitch_card do %>
	  <div class="mini-card-clickable"></div>
  <% end %>

</div>

app/views/pitch_cards/partials/card/_pitch_point.html.erb
<% css_point = point[:name].downcase.tr(' ', '-')%>
<% image_point = point[:name].downcase.tr(' ', '_')%>
<% image_selected = 'points/selected/'+image_point+'.png'%>
<% image_class = "pitch-point-image" %>
<% max_length = pitch_point_max_length %>

<div id="<%= css_point %>" class="form-group row">
  <div class="row-same-height">
	<div class="col-xs-2 col-xs-height col-middle">
	  <a id="<%= css_point %>-selector" data-toggle="tooltip" data-placement="top" title="<%= point[:tooltip] %>">
		<div class="text-center">
		  <%= image_tag_with_at2x image_selected, :class => image_class + " pitch-point-selected" %>
		</div>
	  </a>
	</div>
	<div class="col-xs-10 col-xs-height">

	  <% if point[:suggestible] %>


		  <div class="placard" data-initialize="placard">
			<%= form_for(@suggestion, :url=>new_pitch_card_suggestion_path(@pitch_card), id: "modal-form", method: "get", data: { toggle: "modal", target: "#ajax-modal" }) do |f| %>

				<div class="placard-popup"></div>
				<%= text_area_tag "content", pitch_point_model.value, class: "form-horizontal form-control-borderless form-pitch-point placard-field glass", placeholder: point[:placeholder], maxlength: max_length %>
				<div style="display: none">
				  <%= text_field_tag "original-content", pitch_point_model.value %>
				  <%= text_field_tag "pitch_point_id", pitch_point_model._id %>
				  <%= text_field_tag "pitch_point_name", pitch_point_model.name %>
				</div>
				<div class="placard-footer">
				  <a class="placard-cancel" href="#">Cancel</a> 
				  <% suggest_button_name = "Suggest "+ point[:name] %>
				  <%= f.submit suggest_button_name, class: "btn btn-primary btn-xs placard-accept modal-submit" %>
				</div>
			<% end %>
		  </div>



	  <% elsif point[:top_level_commentable] %>
		  <div class="placard" data-initialize="placard">
			<%= form_for(@comment, :url=>new_pitch_card_comment_path(@pitch_card), id: "modal-form", method: "get", data: { toggle: "modal", target: "#ajax-modal" }) do |f| %>
				<div class="placard-popup"></div>
				<%= text_area_tag "content", pitch_point_model.value, class: "form-horizontal form-control-borderless form-pitch-point placard-field glass", placeholder: point[:placeholder], maxlength: comment_max_length %>
				<div style="display: none">
				  <%= text_field_tag "original-content", pitch_point_model.value %>
				  <%= text_field_tag "pitch_point_id", pitch_point_model._id %>
				  <%= text_field_tag "pitch_point_name", pitch_point_model.name %>
				</div>
				<div class="placard-footer">
				  <a class="placard-cancel" href="#">Cancel</a>
				  <% comment_button_name = "Discuss "+ point[:name] %>
				  <%= f.submit comment_button_name, class: "btn btn-success btn-xs placard-accept modal-submit" %>
				</div>
			<% end %>
		  </div>
	  <% elsif point[:voteable] %>
		  <%= text_area_tag css_point+"-textarea-input", pitch_point_model.value, class: "form-horizontal form-control-borderless form-pitch-point", placeholder: point[:placeholder], disabled: :true %>

		  <div class="row">
			<div class="col-xs-6 text-center">

			  <%=  button_tag(type: 'button', class: 'btn btn-sm btn-success btn-vote feature-coming-soon') do %>
				  <i class="fa fa-check"></i><span> Yes</span>
			  <% end %>

			</div>
			<div class="col-xs-6 text-center">
			  <%=  button_tag(type: 'button', class: 'btn btn-warning btn-sm btn-vote feature-coming-soon') do %>
				  <i class="fa fa-times"></i><span> No</span>
			  <% end %>
			</div>
		  </div>
	  <% end %>

	</div>
  </div>
</div>

app/views/pitch_cards/partials/card/_pitch_point_discourse.html.erb
<% css_point = point[:name].downcase.tr(' ', '-')%>
<% image_point = point[:name].downcase.tr(' ', '_')%>
<% image_selected = 'points/selected/'+image_point+'.png'%>

<div class="col-md-10 col-md-offset-1">
  <div id="<%= css_point %>-discourse-content" class="block block-bordered pitch-card row hidden">
	<div class="row-same-height">
	  <div class="col-xs-2 col-xs-height col-middle">
		<a id="<%= css_point %>-selector">
		  <div class="text-center">
			<%= image_tag_with_at2x image_selected, :class =>  "pitch-point-image-restrained" %>
		  </div>
		</a>
	  </div>
	  <div class="col-xs-8 col-xs-height">
		<h4><%= point[:name] %></h4>
	  </div>
	</div>

	<div class="col-xs-12">
	  <div id="<%= css_point %>-discourse-body">
		<br/>
		<!-- content here -->
	  </div>
	</div>
  </div>
</div>