config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :pitch_cards, except: :index  do
    collection do
      get :initiated, :collabs, :search
    end
    member do
      post :complete, :activate
    end
    resources :comments, only: [:index, :new, :create, :update, :destroy, :initiator_scope, :accept] do
      member do
        post 'initiator_scope'
        post 'accept'
      end
    end
    resources :suggestions, only: [:index, :new, :create, :update, :destroy, :accept] do
      member do
        post 'accept'
      end
    end
  end

  authenticated :user do
    root :to => "dashboard#index", as: :authenticated_root
  end

  root 'welcome#index'

end

app/views/shared/backend/_content_header.erb
<div class="content-header">
  <div class="header-section">
	<h1>
	  <%= content_title %><br>
	  <% if content_subtitle.present? %>
	  	<small><%= content_subtitle %></small>
	  <% end %>
	</h1>
  </div>
</div>

app/views/shared/backend/_footer.html.erb
<!-- Footer -->
<footer class="clearfix">
  <div class="pull-right">
	Crafted with <i class="fa fa-heart text-danger"></i>
  </div>
  <div class="pull-left">
	<span id="year-copy"></span> &copy; PitchHub
  </div>
</footer>
<!-- END Footer -->

app/views/shared/backend/_header.html.erb
<header class="navbar navbar-default">
  <!-- Left Header Navigation -->
  <ul class="nav navbar-nav-custom">

	<li class="visible-xs visible-sm">
	  <a href="javascript:void(0)" onclick="App.sidebar('toggle-sidebar');
			  this.blur();">
		<i class="fa fa-bars fa-fw"></i>
	  </a>
	</li>

	<li>
	  <%= link_to(new_pitch_card_path) do %>
		  <i class="fa fa-plus"></i>
	  <% end %>
	</li>

  </ul>
  <!-- END Left Header Navigation -->

  <!-- Search Form -->
  <form action="/pitch_cards/search" method="get" class="navbar-form-custom" role="search">
	<div class="form-group">
	  <input type="text" id="top-search" name="top-search" class="form-control" placeholder="Search..." size="100">
	</div>
	<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
  </form>
  <!-- END Search Form -->

  <!-- Right Header Navigation -->
  <ul class="nav navbar-nav-custom pull-right">
	<!-- User Dropdown -->
	<li class="dropdown">
	  <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
		<span class="hidden-xs"><%= current_user.first_name %></span>
		<%= image_tag_with_at2x 'user.png' %>
		<span class="caret"></span>
	  </a>
	  <ul class="dropdown-menu dropdown-custom dropdown-menu-right" style="z-index: 10000000;">
		<li class="dropdown-header text-center">Account</li>
		<li>
		  <a href="#" class="page-coming-soon">
			<i class="fa fa-question fa-fw pull-right"></i>
			FAQ
		  </a>
		</li>
		<li class="divider"></li>
		<li>
		  <a href="#" class="page-coming-soon">
			<i class="fa fa-user fa-fw pull-right"></i>
			Settings
		  </a>
		</li>
		<li class="divider"></li>
		<li>

		  <%= link_to(destroy_user_session_path, :method => :delete) do %>
			  <i class="fa fa-ban fa-fw pull-right"></i> Logout
		  <% end %>

		</li>
	  </ul>
	</li>
	<!-- END User Dropdown -->
  </ul>
  <!-- END Right Header Navigation -->
</header>
<!-- END Header -->

app/views/shared/backend/_sidebar.html.erb
<!-- Main Sidebar -->
<div id="sidebar">
  <!-- Wrapper for scrolling functionality -->
  <div id="sidebar-scroll">
	<!-- Sidebar Content -->
	<div class="sidebar-content">
	  <!-- Brand -->
	  <a href="/" class="sidebar-brand text-center">
		<span id="pitchhub-brand-text" class="sidebar-nav-mini-hide">pitchhub</span>
	  </a>
	  <!-- END Brand -->

	  <!-- Sidebar Navigation -->
	  <ul class="sidebar-nav">
		<li>
		  <%= active_link_to("/", :active => :exclusive )do %>
			  <i class="fa fa-th-list sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Dashboard</span>
		  <% end %>
		</li>
		<li class="sidebar-header">
		  <span class="sidebar-header-title">Pitch Cards</span>
		</li>
		<li>
		  <%= active_link_to(initiated_pitch_cards_path, :active => :exclusive) do %>
			  <i class="fa fa-star-o sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Initiated</span>
		  <% end %>
		</li>
		<li>
		  <%= active_link_to(collabs_pitch_cards_path, :active => :exclusive) do %>
			  <i class="fa fa-star sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Collaborated</span>
		  <% end %>
		</li>
		<li class="sidebar-header">
		  <span class="sidebar-header-title">Settings</span>
		</li>
		<li>
		  <a href="#" class="page-coming-soon"><i class="fa fa-users sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Groups</span></a>
		</li>
		<li>
		  <a href="#" class="page-coming-soon"><i class="fa fa-info sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">About</span></a>
		</li>
	  </ul>
	  <!-- END Sidebar Navigation -->

	</div>
	<!-- END Sidebar Content -->
  </div>
  <!-- END Wrapper for scrolling functionality -->
</div>
<!-- END Main Sidebar -->